//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        [Required]
        [Display(Name ="User Name")]
        public string user_name { get; set; }


        [Display(Name = "Password")]
        [Required]
        public string pass_word { get; set; }

        [Display(Name = "Admin Type")]
        [Required]
        public string admin_type { get; set; }
    }
}
