//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int adid { get; set; }
        public Nullable<int> pregid { get; set; }

        [Display(Name = "Product Name")]
        [Required]
        public string product_name { get; set; }

        [Display(Name = "Product Category")]
        [Required]
        public string product_category { get; set; }
        public string image { get; set; }

        [Display(Name = "Product Quantity")]
        [Required]
        public string product_quantity { get; set; }


        [Display(Name = "Price Per Unit")]
        [Required]
        public string price_per_unit { get; set; }


        [Display(Name = "Desription")]
        [Required]
        public string description { get; set; }

        [Display(Name = "Phone")]
        [Required]
        public string pphone { get; set; }


        [Display(Name = "Division")]
        [Required]
        public string pdivision { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
